package com.xgen.mongot.index;

import com.xgen.mongot.util.BsonUtils;
import java.util.ArrayList;
import java.util.List;
import org.bson.BsonDocument;
import org.bson.BsonDouble;
import org.bson.BsonInt64;
import org.bson.BsonString;
import org.bson.RawBsonDocument;

/**
 * IntermediateMetricBucket represents one component of a metric produced for a metrics collector
 * query run against a sharded collection (or one index partition). A metric is decomposed into
 * algebraic components ({@link Component}) so that partial results can be merged exactly: the
 * merged {@code sum} and {@code count} are their totals, and the merged {@code min}/{@code max} are
 * the extremes. These buckets are later merged using the plan generated by {@link
 * com.xgen.mongot.server.command.search.ShardedSearchPlanner}, which relies on the field names
 * declared here.
 *
 * <pre>
 *   {type: "metric", tag: "&lt;metric name&gt;", bucket: "sum",   value: 12.5}
 *   {type: "metric", tag: "&lt;metric name&gt;", bucket: "count", count: 3}
 * </pre>
 */
public record IntermediateMetricBucket(String tag, Component component, double value) {

  public static final String TYPE_FIELD = "type";
  public static final String TAG_FIELD = "tag";
  public static final String BUCKET_FIELD = "bucket";
  /** Holds the double payload of {@code sum}, {@code min} and {@code max} components. */
  public static final String VALUE_FIELD = "value";
  /** Holds the long payload of the {@code count} component (same field as facet/count docs). */
  public static final String COUNT_FIELD = "count";
  public static final String TYPE = "metric";

  public enum Component {
    SUM("sum"),
    COUNT("count"),
    MIN("min"),
    MAX("max");

    private final String wireName;

    Component(String wireName) {
      this.wireName = wireName;
    }

    public String getWireName() {
      return this.wireName;
    }
  }

  /**
   * Decomposes one metric's accumulated state into intermediate buckets. {@code sum} and {@code
   * count} are always emitted; {@code min} and {@code max} only when at least one value was seen,
   * so that empty partials do not distort the merged extremes.
   */
  public static List<IntermediateMetricBucket> decompose(
      String tag, double sum, long count, double min, double max) {
    List<IntermediateMetricBucket> buckets = new ArrayList<>(4);
    buckets.add(new IntermediateMetricBucket(tag, Component.SUM, sum));
    buckets.add(new IntermediateMetricBucket(tag, Component.COUNT, count));
    if (count > 0) {
      buckets.add(new IntermediateMetricBucket(tag, Component.MIN, min));
      buckets.add(new IntermediateMetricBucket(tag, Component.MAX, max));
    }
    return buckets;
  }

  public RawBsonDocument toRawBson() {
    BsonDocument document =
        new BsonDocument(TYPE_FIELD, new BsonString(TYPE))
            .append(TAG_FIELD, new BsonString(this.tag))
            .append(BUCKET_FIELD, new BsonString(this.component.getWireName()));
    if (this.component == Component.COUNT) {
      document.append(COUNT_FIELD, new BsonInt64((long) this.value));
    } else {
      document.append(VALUE_FIELD, new BsonDouble(this.value));
    }
    return BsonUtils.documentToRaw(document);
  }
}
